### ISSUE TITLE
我看到了您在看雪发表的那个自己实现Log类，能否弄一个纯java版本因为，native这东西要给所有app弄得话麻烦一点

### ISSUE THREAD

**Issue by lozn00** [smartdone/dexdump#4]
我开发了一个工具，可以hook所有字符串，您这样说的话看来爱加密这样的流氓，我还是没法输出日志的。

但是自己再为每一个app弄一个 so打印也不太好

**Comment by smartdone** [comment]
按理说用java也是可以的，他写的是一个结构体数组到一个设备文件，还没尝试过
