### ISSUE TITLE
能不能写下稍微详细的文档。小白有点不懂libhook.so怎么来

### ISSUE THREAD

**Issue by orzlenmo** [smartdone/dexdump#9]
能不能写下稍微详细的过程。小白有点不懂libhook.so怎么来

**Comment by smartdone** [comment]
libhook.so是编译出来的apk里面的，解压在libs下面就有。你可以用我这个纯frida写的[https://github.com/smartdone/Frida-Scripts/tree/master/unpack](https://github.com/smartdone/Frida-Scripts/tree/master/unpack)，用起来比较方便，部分抽类的也可以修复

**Comment by orzlenmo** [comment]
用了哪个报了这个错误，是什么情况，手机是华为mate9 pro版 android 8.0系统。
![qq 20180904173839](https://user-images.githubusercontent.com/14181981/45023652-8d17c500-b069-11e8-93a0-d2e0984feaad.png)

C:\Users\Administrator>frida -R -f {com.dehui.qsjpq} -l unpack.js

***
Failed to load the Frida native extension: DLL load failed: 找不到指定的模块。
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\Scripts\frida-script.py", line 11, in
 <module>
    load_entry_point('frida-tools==1.2.1', 'console_scripts', 'frida')()
  File "c:\program files (x86)\python36-32\lib\site-packages\frida_tools\repl.py
", line 22, in main
    import frida
  File "c:\program files (x86)\python36-32\lib\site-packages\frida\__init__.py",
 line 24, in <module>
    raise ex
  File "c:\program files (x86)\python36-32\lib\site-packages\frida\__init__.py",
 line 7, in <module>
    import _frida
ImportError: DLL load failed: 找不到指定的模块。

**Comment by orzlenmo** [comment]
谢谢。我试试哪个

**Comment by orzlenmo** [comment]
![image](https://user-images.githubusercontent.com/14181981/45024172-0368f700-b06b-11e8-8f43-47e43b637ff9.png)
![image](https://user-images.githubusercontent.com/14181981/45024226-1f6c9880-b06b-11e8-8083-74705dfd38da.png)

C:\Users\Administrator>frida -R -f {com.dehui.qsjpq} -l unpack.js

***
Failed to load the Frida native extension: DLL load failed: 找不到指定的模块。
Please ensure that the extension was compiled for Python 3.x.
***

Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\Scripts\frida-script.py", line 11, in
 <module>
    load_entry_point('frida-tools==1.2.1', 'console_scripts', 'frida')()
  File "c:\program files (x86)\python36-32\lib\site-packages\frida_tools\repl.py
", line 22, in main
    import frida
  File "c:\program files (x86)\python36-32\lib\site-packages\frida\__init__.py",
 line 24, in <module>
    raise ex
  File "c:\program files (x86)\python36-32\lib\site-packages\frida\__init__.py",
 line 7, in <module>
    import _frida
ImportError: DLL load failed: 找不到指定的模块。

C:\Users\Administrator>pip install frida
Requirement already satisfied: frida in c:\program files (x86)\python36-32\lib\s
ite-packages
You are using pip version 9.0.3, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.
这个问题作者有碰倒过吗？查了了百度很多说只能重装

**Comment by smartdone** [comment]
没有遇到，看来要重新装一下，他没找到dll

**Comment by orzlenmo** [comment]
昨天哪个问题是解决了。原因是我是win 7系统装的python 36-32位的frida没有这个版本
![qq 20180905101803](https://user-images.githubusercontent.com/14181981/45067270-01e41100-b0f5-11e8-918a-3fd96724886c.png)

重装下python 37的就好了。
![qq 20180905101624](https://user-images.githubusercontent.com/14181981/45067228-c8aba100-b0f4-11e8-9f5d-e491c0dc78c5.png)
这个算是成功了吗？
大佬有没有qq或者什么联系方式。

**Comment by smartdone** [comment]
要在手机上面放一个frida-server,启动起来 https://github.com/frida/frida/releases 看你手机是arm的还是arm64的，下载对应版本，启动起来，然后转发端口27042.参考这个https://blog.csdn.net/freakishfox/article/details/78302741

**Comment by orzlenmo** [comment]
是我问题。小白刚接触frida所以有点不懂。我继续百度

**Comment by smartdone** [comment]
哈哈哈，加油好好学

**Comment by orzlenmo** [comment]
能不能加个qq，交个朋友也好。我的qq：826855212
